basePath: /
definitions:
  models.CreateTokenResponse:
    properties:
      success:
        description: Success type is bool
        type: boolean
      token:
        description: Token type is string
        type: string
    type: object
info:
  contact:
    email: burakscr@gmail.com
    name: Burak SEÇER
    url: http://www.buraksecer.com
  description: Go Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Project
  version: "1.0"
paths:
  /create-token:
    post:
      consumes:
      - application/json
      description: Create new token
      operationId: create-token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.CreateTokenResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.CreateTokenResponse'
      summary: Create new token
swagger: "2.0"
