basePath: /
definitions:
  models.CreateTokenRequest:
    properties:
      password:
        default: "1"
        description: Password type is string and we validated
        type: string
      username:
        default: buraksecer
        description: Username type is string and we validated
        type: string
    type: object
  models.CreateTokenResponse:
    properties:
      success:
        description: Success type is bool
        type: boolean
      token:
        description: Token type is string
        type: string
    type: object
  responses.JSONInternalErrorResult:
    properties:
      code:
        example: 500
        type: integer
      data: {}
      message:
        example: Internal Error
        type: string
    type: object
  responses.JSONSuccessResult:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      message:
        example: Success
        type: string
    type: object
info:
  contact:
    email: burakscr@gmail.com
    name: Burak SEÇER
    url: http://www.buraksecer.com
  description: Go Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Project
  version: "1.0"
paths:
  /create-token:
    post:
      consumes:
      - application/json
      description: Create new token
      operationId: create-token
      parameters:
      - description: Create new token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/models.CreateTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responses.JSONSuccessResult'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/models.CreateTokenResponse'
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/responses.JSONSuccessResult'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/responses.JSONInternalErrorResult'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
      summary: Create new token
swagger: "2.0"
