basePath: /
info:
  contact:
    email: burakscr@gmail.com
    name: Burak SEÇER
    url: http://www.buraksecer.com
  description: Go Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Project
  version: "1.0"
paths: {}
swagger: "2.0"
